"""empty message

Revision ID: c3323c013b17
Revises: 
Create Date: 2023-03-28 14:39:21.508467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3323c013b17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('patient')
    ##op.drop_table('doctor')
    # ### end Alembic commands ###
    op.add_column('appointment', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.add_column('appointment', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointment', 'doctor', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'appointment', 'patient', ['patient_id'], ['id'])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('appo_location', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('twiter_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('linkedin_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('specialities', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('upcoming_appo', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('past_appo', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='doctor_pkey')
    )
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appo_day', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('appo_time', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('appo_available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='appointment_pkey')
    )
    op.create_table('patient',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('appo_location', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('health_insurance_provider', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('health_insurance_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('seeking_specialities', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('concern_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('upcoming_appo', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('past_appo', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='patient_pkey')
    )
    # ### end Alembic commands ###
